name: github_client
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^8.1.0
  flutter_web_auth_2: ^3.1.1
  go_router: ^13.2.0
  graphql: ^5.2.0-beta.7
  http: ^1.2.1
  provider: ^6.1.2
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mocktail: ^1.0.3
  mockito: ^5.4.4
  fake_async: ^1.3.1


flutter:
  uses-material-design: true
